name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 97bc53c8-2218-4d59-82bf-1fcc406de65a
          heroku_app_name: iamtakahashimaaya
          heroku_email: takahashimaaya@protonmail.com
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_CONFIG_FILE_URL: https://gist.githubusercontent.com/takahashimaaya/683c8b235bb2624f860bec87944648e1/raw/config.env
